### ISSUE TITLE
Linting errors and overall code guidelines are not always what they should be in Angular

### ISSUE THREAD

**Issue by TriangleJuice** [digipolisantwerp/starter-kit-ui_app_nodejs#33]
When opening a freshly made Angular project with the starter kit, I get lots of linting errors, like:
- no prefixes used on components
- no suffixes used in components
- wrong indentation
- etc.

Ideally these should all be eliminated.

**Comment by MichaelCastiau** [comment]
https://github.com/digipolisantwerp/starter-kit-ui_app_nodejs/pull/34
