### ISSUE TITLE
start faalt

### ISSUE THREAD

**Issue by webspin** [digipolisantwerp/starter-kit-ui_app_nodejs#71]
Geprobeerd met config:
? Which BFF technology would you like? Node.js
? Which frontend technology would you like? ReactJs
? Which database would you like? I don't need a database
? Do you want your app to include Digipolis authentication? Yes
? Which branding do you want to use? Antwerp
? Do you want to use the Flexbox grid? Yes
? Do you want to add basic routing? Yes

node version: v16.15.1

npm ERR! code 1
npm ERR! path /app/frontend/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/lib/node_modules/node/bin/node /app/frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=

**Comment by TriangleJuice** [comment]
Ik heb het ook even bekeken en vond dat er wat dingen veranderd zijn voor nieuwere versies van Node. Er staat een PR open met een fix.

**Comment by TriangleJuice** [comment]
@webspin Het zou in orde moeten zijn in v4.0.1
